version: "3"
services:
    conda:
        build: .
        container_name: conda
        ports: 
            - "8888:8888"
        volumes:
            - "./notebooks:/opt/notebooks"
        command: /bin/bash -c "/opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root"